device: 3 #cuda 0 1 2 3 cpu
data_dir: "/data/alex/original_torch"
log_dir: "runs/" # "/data/alex/original_torch/runs/" # Not in Alex's original code
class_name: "fx"
batch_size: 22 # 7 resnet152, 15 resnet18, 24 default
run_name: "unified_boundary_w1"
epochs: 60
save_every: None
use_channels: [0,1,2]
early_stopping: 15 # Not in Alex's original code
loss_opts:
  name: "unified"
  masked: True
  # weights: [0.5, 0.5]
  # label_smoothing: 0.1
  # sigma: 0
model_opts:
  args: 
    inchannels: 3
    outchannels: 2
    net_depth: 4
    # dropout: [0.1,0.1,0.2,0.2,0.3] #0.2 # 
    # spatial: True
    # first_channel_output: 16 #64
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["Background", "fx"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
reg_opts:
  l1_reg: 0.00001